
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox boxLayout;

	private global::Gtk.Image image5;

	private global::Gtk.Notebook tabLayout;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.FileChooserButton fileHex;

	private global::Gtk.Label label6;

	private global::Gtk.Label lblHexStatistics;

	private global::Gtk.Button btnHexProgram;

	private global::Gtk.Label lblOldHexWarning;

	private global::Gtk.Button btnHexRefresh;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label5;

	private global::Gtk.Label label4;

	private global::Gtk.ProgressBar progressBar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Unified Programmer");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.boxLayout = new global::Gtk.VBox ();
		this.boxLayout.Name = "boxLayout";
		this.boxLayout.Spacing = 6;
		// Container child boxLayout.Gtk.Box+BoxChild
		this.image5 = new global::Gtk.Image ();
		this.image5.Name = "image5";
		this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ProgrammerGUI.watson_dash_smaller.png");
		this.boxLayout.Add (this.image5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.boxLayout[this.image5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child boxLayout.Gtk.Box+BoxChild
		this.tabLayout = new global::Gtk.Notebook ();
		this.tabLayout.CanFocus = true;
		this.tabLayout.Name = "tabLayout";
		this.tabLayout.CurrentPage = 0;
		// Container child tabLayout.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fileHex = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
		this.fileHex.WidthRequest = 489;
		this.fileHex.Name = "fileHex";
		this.fileHex.ShowHidden = true;
		this.fixed2.Add (this.fileHex);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fileHex]));
		w2.X = 8;
		w2.Y = 34;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Select the intel Hex file to be programmed:");
		this.fixed2.Add (this.label6);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
		w3.X = 11;
		w3.Y = 12;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblHexStatistics = new global::Gtk.Label ();
		this.lblHexStatistics.WidthRequest = 477;
		this.lblHexStatistics.HeightRequest = 65;
		this.lblHexStatistics.Name = "lblHexStatistics";
		this.lblHexStatistics.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Program Memory Available:</b> XX\n<b>Data Memory Available:</b> YY\n");
		this.lblHexStatistics.UseMarkup = true;
		this.lblHexStatistics.MaxWidthChars = 57;
		this.fixed2.Add (this.lblHexStatistics);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblHexStatistics]));
		w4.X = 16;
		w4.Y = 80;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnHexProgram = new global::Gtk.Button ();
		this.btnHexProgram.WidthRequest = 115;
		this.btnHexProgram.Sensitive = false;
		this.btnHexProgram.CanFocus = true;
		this.btnHexProgram.Name = "btnHexProgram";
		this.btnHexProgram.UseUnderline = true;
		// Container child btnHexProgram.Gtk.Container+ContainerChild
		global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w6 = new global::Gtk.HBox ();
		w6.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w7 = new global::Gtk.Image ();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-jump-to", global::Gtk.IconSize.Menu);
		w6.Add (w7);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Program");
		w9.UseUnderline = true;
		w6.Add (w9);
		w5.Add (w6);
		this.btnHexProgram.Add (w5);
		this.fixed2.Add (this.btnHexProgram);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnHexProgram]));
		w13.X = 379;
		w13.Y = 241;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblOldHexWarning = new global::Gtk.Label ();
		this.lblOldHexWarning.Name = "lblOldHexWarning";
		this.lblOldHexWarning.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Warning!</b> The file you're programming hasn't changed\nsince the previous programming. (Did you recompile?)");
		this.lblOldHexWarning.UseMarkup = true;
		this.lblOldHexWarning.Angle = 360;
		this.fixed2.Add (this.lblOldHexWarning);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblOldHexWarning]));
		w14.X = 13;
		w14.Y = 230;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnHexRefresh = new global::Gtk.Button ();
		this.btnHexRefresh.Sensitive = false;
		this.btnHexRefresh.CanFocus = true;
		this.btnHexRefresh.Name = "btnHexRefresh";
		this.btnHexRefresh.UseUnderline = true;
		// Container child btnHexRefresh.Gtk.Container+ContainerChild
		global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w16 = new global::Gtk.HBox ();
		w16.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w17 = new global::Gtk.Image ();
		w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
		w16.Add (w17);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w19 = new global::Gtk.Label ();
		w19.LabelProp = global::Mono.Unix.Catalog.GetString ("_Refresh");
		w19.UseUnderline = true;
		w16.Add (w19);
		w15.Add (w16);
		this.btnHexRefresh.Add (w15);
		this.fixed2.Add (this.btnHexRefresh);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnHexRefresh]));
		w23.X = 419;
		w23.Y = 71;
		this.tabLayout.Add (this.fixed2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Microcontroller Only");
		this.tabLayout.SetTabLabel (this.fixed2, this.label1);
		this.label1.ShowAll ();
		// Notebook tab
		global::Gtk.Label w25 = new global::Gtk.Label ();
		w25.Visible = true;
		this.tabLayout.Add (w25);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("FPGA Only");
		this.tabLayout.SetTabLabel (w25, this.label2);
		this.label2.ShowAll ();
		// Notebook tab
		global::Gtk.Label w26 = new global::Gtk.Label ();
		w26.Visible = true;
		this.tabLayout.Add (w26);
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Full Kit");
		this.tabLayout.SetTabLabel (w26, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w27 = new global::Gtk.Label ();
		w27.Visible = true;
		this.tabLayout.Add (w27);
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Ready Modules");
		this.tabLayout.SetTabLabel (w27, this.label5);
		this.label5.ShowAll ();
		// Notebook tab
		global::Gtk.Label w28 = new global::Gtk.Label ();
		w28.Visible = true;
		this.tabLayout.Add (w28);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Advanced");
		this.tabLayout.SetTabLabel (w28, this.label4);
		this.label4.ShowAll ();
		this.boxLayout.Add (this.tabLayout);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.boxLayout[this.tabLayout]));
		w29.Position = 1;
		// Container child boxLayout.Gtk.Box+BoxChild
		this.progressBar = new global::Gtk.ProgressBar ();
		this.progressBar.WidthRequest = 505;
		this.progressBar.HeightRequest = 0;
		this.progressBar.Name = "progressBar";
		this.progressBar.Text = global::Mono.Unix.Catalog.GetString (" ");
		this.boxLayout.Add (this.progressBar);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.boxLayout[this.progressBar]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.Add (this.boxLayout);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 517;
		this.DefaultHeight = 450;
		this.lblHexStatistics.Hide ();
		this.lblOldHexWarning.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
