
// This file has been generated by the GUI designer. Do not modify.
namespace ProgrammerGUI
{
	public partial class DeviceWaiting
	{
		private global::Gtk.Label lblWaiting;

		private global::Gtk.ProgressBar progressbar3;

		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProgrammerGUI.DeviceWaiting
			this.Name = "ProgrammerGUI.DeviceWaiting";
			this.Title = global::Mono.Unix.Catalog.GetString ("Waiting for device...");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child ProgrammerGUI.DeviceWaiting.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblWaiting = new global::Gtk.Label ();
			this.lblWaiting.Name = "lblWaiting";
			this.lblWaiting.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
			w1.Add (this.lblWaiting);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1[this.lblWaiting]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.progressbar3 = new global::Gtk.ProgressBar ();
			this.progressbar3.Name = "progressbar3";
			this.progressbar3.Text = "";
			w1.Add (this.progressbar3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1[this.progressbar3]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Internal child ProgrammerGUI.DeviceWaiting.ActionArea
			global::Gtk.HButtonBox w4 = this.ActionArea;
			w4.Name = "dialog1_ActionArea";
			w4.Spacing = 10;
			w4.BorderWidth = ((uint)(5));
			w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4[this.buttonCancel]));
			w5.Expand = false;
			w5.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 139;
			this.Show ();
		}
	}
}
